export const foods = [
  { id: 1, name: "Margherita Pizza", description: "Classic cheese pizza with tomato and basil", price: 299, rating: 4.3 },
  { id: 2, name: "Chicken Biryani", description: "Hyderabadi style aromatic biryani", price: 220, rating: 4.6 },
  { id: 3, name: "Veg Burger", description: "Crispy patty with lettuce and mayo", price: 120, rating: 3.9 },
  { id: 4, name: "Paneer Butter Masala", description: "Creamy tomato gravy with soft paneer cubes", price: 180, rating: 4.4 },
  { id: 5, name: "Cold Coffee", description: "Iced coffee blended with cream", price: 90, rating: 4.1 },
  { id: 6, name: "Pasta Alfredo", description: "Creamy white sauce pasta", price: 240, rating: 4.0 },
  { id: 7, name: "Chicken Wings", description: "Spicy glazed wings", price: 260, rating: 4.5 },
  { id: 8, name: "Caesar Salad", description: "Fresh romaine lettuce with parmesan", price: 150, rating: 3.8 },
  { id: 9, name: "Masala Dosa", description: "Crispy dosa stuffed with potato masala", price: 90, rating: 4.2 },
  { id: 10, name: "Sushi Platter", description: "Assorted sushi rolls", price: 499, rating: 4.7 },
  { id: 11, name: "Falafel Wrap", description: "Chickpea patties wrapped in pita", price: 160, rating: 3.7 },
  { id: 12, name: "French Fries", description: "Crispy golden fries", price: 80, rating: 4.0 },
  { id: 13, name: "Tandoori Chicken", description: "Char-grilled chicken marinated in spices", price: 280, rating: 4.6 },
  { id: 14, name: "Chocolate Shake", description: "Thick milkshake with chocolate syrup", price: 140, rating: 4.1 },
  { id: 15, name: "Veg Fried Rice", description: "Stir-fried rice with veggies", price: 110, rating: 3.9 },
  { id: 16, name: "Chicken Momos", description: "Steamed dumplings stuffed with chicken", price: 100, rating: 4.3 },
  { id: 17, name: "Hakka Noodles", description: "Indo-Chinese style stir-fried noodles", price: 130, rating: 4.0 },
  { id: 18, name: "Grilled Sandwich", description: "Paneer and veggie grilled sandwich", price: 90, rating: 3.8 },
  { id: 19, name: "Gulab Jamun", description: "Soft fried balls soaked in sugar syrup", price: 70, rating: 4.5 },
  { id: 20, name: "Pani Puri", description: "Crisp puris filled with tangy water", price: 50, rating: 4.2 },
  { id: 21, name: "Beef Steak", description: "Grilled medium-rare steak", price: 650, rating: 4.7 },
  { id: 22, name: "Fish Curry", description: "Coastal style spicy fish curry", price: 230, rating: 4.3 },
  { id: 23, name: "Idli Sambar", description: "Steamed rice cakes with lentil soup", price: 60, rating: 4.1 },
  { id: 24, name: "Veg Thali", description: "Assorted Indian dishes in one platter", price: 180, rating: 4.0 },
  { id: 25, name: "Chicken Shawarma", description: "Roasted chicken wrapped with garlic sauce", price: 130, rating: 4.4 },
  { id: 26, name: "Margarita Mocktail", description: "Citrus blend with a salty rim", price: 160, rating: 3.9 },
  { id: 27, name: "Ice Cream Sundae", description: "Vanilla ice cream with chocolate drizzle", price: 120, rating: 4.2 },
  { id: 28, name: "Veg Spring Roll", description: "Crispy rolls stuffed with veggies", price: 90, rating: 3.8 },
  { id: 29, name: "Butter Chicken", description: "Rich creamy tomato gravy with chicken", price: 260, rating: 4.7 },
  { id: 30, name: "Garlic Bread", description: "Toasted bread with garlic butter", price: 80, rating: 4.0 },
  { id: 31, name: "Ramen Bowl", description: "Japanese noodles with broth and toppings", price: 350, rating: 4.5 },
  { id: 32, name: "Stuffed Paratha", description: "Flaky paratha filled with potato stuffing", price: 60, rating: 4.1 },
  { id: 33, name: "Greek Salad", description: "Feta cheese with veggies and olives", price: 170, rating: 3.8 },
  { id: 34, name: "Chicken Popcorn", description: "Bite-sized crispy chicken", price: 120, rating: 4.3 },
  { id: 35, name: "Pav Bhaji", description: "Spicy mashed vegetables with soft buns", price: 100, rating: 4.4 },
  { id: 36, name: "Kebabs", description: "Smoky grilled minced meat skewers", price: 220, rating: 4.5 },
  { id: 37, name: "Tomato Soup", description: "Creamy tomato soup with herbs", price: 70, rating: 3.7 },
  { id: 38, name: "Veg Pizza", description: "Loaded with veggies and cheese", price: 250, rating: 4.0 },
  { id: 39, name: "Berry Smoothie", description: "Mixed berries blended with yogurt", price: 150, rating: 4.2 },
  { id: 40, name: "Samosa", description: "Fried pastry stuffed with potato", price: 20, rating: 4.1 },
  { id: 41, name: "BBQ Chicken Pizza", description: "Pizza topped with BBQ chicken chunks", price: 350, rating: 4.5 },
  { id: 42, name: "Fried Chicken Bucket", description: "Crispy fried chicken pieces", price: 399, rating: 4.6 },
  { id: 43, name: "Chocolate Brownie", description: "Rich fudgy brownie", price: 90, rating: 4.4 },
  { id: 44, name: "Nachos & Cheese", description: "Corn nachos loaded with cheese", price: 160, rating: 4.0 },
  { id: 45, name: "Mushroom Soup", description: "Creamy soup with mushroom chunks", price: 80, rating: 3.9 },
  { id: 46, name: "Chicken Caesar Wrap", description: "Grilled chicken with Caesar dressing", price: 180, rating: 4.2 },
  { id: 47, name: "Veg Puff", description: "Crispy puff with spiced vegetable filling", price: 25, rating: 3.8 },
  { id: 48, name: "Dal Tadka", description: "Yellow lentils tempered with spices", price: 100, rating: 4.1 },
  { id: 49, name: "Chole Bhature", description: "Spicy chickpeas with fried bread", price: 110, rating: 4.5 },
  { id: 50, name: "Mango Lassi", description: "Sweet yogurt drink with mango pulp", price: 90, rating: 4.3 }
]
